p2v: virt-p2v-make-disk: Make os-version parameter optional.
Having to choose the os-version of the virt-p2v disk was confusing.
Users thought it had something to do with the physical machine being
converted.

In some cases, virt-p2v-make-disk can now choose a suitable os-version
for the user.  Usually it's the latest numeric version of Fedora or
Debian, depending on the host distro.  If we don't recognize the host
distro, we bail and ask the user to choose, but this is still an
improvement.

(cherry picked from commit 3aaa4c9419d539dada31004b47121bbaac5241c6)

diff --git a/p2v/virt-p2v-make-disk.in b/p2v/virt-p2v-make-disk.in
--- a/p2v/virt-p2v-make-disk.in
+++ b/p2v/virt-p2v-make-disk.in
@@ -38,7 +38,7 @@ upload=
 usage ()
 {
     echo "Usage:"
-    echo "  $program [--options] -o /dev/sdX os-version"
+    echo "  $program [--options] -o /dev/sdX [os-version]"
     echo
     echo "Read $program(1) man page for more information."
     exit $1
@@ -71,12 +71,30 @@ if [ -z "$output" ]; then
     exit 1
 fi
 
-if [ $# -ne 1 ]; then
-    echo "$program: Missing os-version.  See $program(1)."
+if [ $# -gt 1 ]; then
+    echo "$program: Too many parameters.  See $program(1)."
     exit 1
 fi
 
-osversion="$1"
+if [ $# -eq 1 ]; then
+    osversion="$1"
+else
+    # If osversion was not set, then we must guess a good value
+    # based on the host distro.
+    if test -f /etc/redhat-release; then
+        osversion="$(virt-builder -l | sort |
+                       @AWK@ '/^fedora-[1-9]/ {print $1}' | tail -1)"
+    elif test -f /etc/debian_version; then
+        osversion="$(virt-builder -l | sort |
+                       @AWK@ '/^debian-[1-9]/ {print $1}' | tail -1)"
+    fi
+    if [ "x$osversion" = "x" ]; then
+        echo "$program: unable to guess a suitable os-version."
+        echo "You must supply one on the command line and output of 'virt-builder -l'."
+        echo "See $program(1) for further details."
+        exit 1
+    fi
+fi
 
 # Create a temporary directory and clean it up when we finish.
 tmpdir="$(mktemp -d)"
