p2v: virt-p2v-make-disk: Allow --arch parameter to be supplied.
This allows you to build a 32 bit virt-p2v USB key, even on a 64 bit
host.

Because of problems with the Fedora build system it's unfortunately
not easy to build a 32 bit virt-p2v binary, so this patch punts on
this issue and assumes that the user can supply the binary themselves.

diff --git a/p2v/virt-p2v-make-disk.in b/p2v/virt-p2v-make-disk.in
--- a/p2v/virt-p2v-make-disk.in
+++ b/p2v/virt-p2v-make-disk.in
@@ -22,9 +22,23 @@ unset CDPATH
 program="virt-p2v-make-disk"
 version="@PACKAGE_VERSION@"
 
+# Deal with stupid autotools libexecdir-not-expandable crap.
+prefix="@prefix@"
+exec_prefix="@exec_prefix@"
+libexecdir="@libexecdir@"
+
+if [ -n "$VIRT_P2V_DATA_DIR" ]; then
+    datadir="$VIRT_P2V_DATA_DIR"
+    host_libexecdir="$VIRT_P2V_DATA_DIR"
+else
+    datadir="@datadir@/virt-p2v"
+    host_libexecdir="@libexecdir@"
+fi
+
+# Parse the command line arguments.
 TEMP=`getopt \
         -o o:V \
-        --long help,inject-ssh-identity:,output:,version \
+        --long arch:,help,inject-ssh-identity:,output:,version \
         -n $program -- "$@"`
 if [ $? != 0 ]; then
     echo "$program: problem parsing the command line arguments"
@@ -46,6 +60,9 @@ usage ()
 
 while true; do
     case "$1" in
+        --arch)
+            arch="$2"
+            shift 2;;
         --inject-ssh-identity)
             upload="--upload $2:/var/tmp/id_rsa"
             shift 2;;
@@ -78,6 +95,23 @@ fi
 
 osversion="$1"
 
+if [ -n "$arch" ]; then
+    arch_option="--arch $arch"
+    virt_p2v_binary="$host_libexecdir/virt-p2v.$arch"
+else
+    virt_p2v_binary="$host_libexecdir/virt-p2v"
+fi
+
+if [ ! -f "$virt_p2v_binary" ]; then
+    echo "$0: cannot find $virt_p2v_binary"
+    if [ -n "$arch" ]; then
+        echo "You used the '--arch' option, so it's likely that you will need to build"
+        echo "an virt-p2v.$arch binary yourself."
+        echo "See guestfs-building(1) section BUILDING i686 32 BIT VIRT-P2V for help."
+    fi
+    exit 1
+fi
+
 # Create a temporary directory and clean it up when we finish.
 tmpdir="$(mktemp -d)"
 cleanup ()
@@ -85,19 +119,6 @@ cleanup ()
     rm -rf $tmpdir
 }
 trap cleanup INT QUIT TERM EXIT ERR
-
-# Deal with stupid autotools libexecdir-not-expandable crap.
-prefix="@prefix@"
-exec_prefix="@exec_prefix@"
-libexecdir="@libexecdir@"
-
-if [ -n "$VIRT_P2V_DATA_DIR" ]; then
-    datadir="$VIRT_P2V_DATA_DIR"
-    host_libexecdir="$VIRT_P2V_DATA_DIR"
-else
-    datadir="@datadir@/virt-p2v"
-    host_libexecdir="@libexecdir@"
-fi
 
 # Variations depending on the target distro.  The main difference
 # is in the list of distro packages we add to the base appliance.
@@ -155,13 +176,14 @@ done < $depsfile
 # could provide a sysvinit fallback if required.
 virt-builder "$osversion"                                       \
     --output "$output"                                          \
+    $arch_option						\
     --update                                                    \
     --install "$install"                                        \
     --root-password password:p2v                                \
     --upload "$datadir"/issue:/etc/issue                        \
     --upload "$datadir"/issue:/etc/issue.net                    \
     --mkdir "$libexecdir"                                       \
-    --upload "$host_libexecdir"/virt-p2v:"$libexecdir"          \
+    --upload "$virt_p2v_binary":"$libexecdir"/virt-p2v          \
     --chmod 0755:"$libexecdir"/virt-p2v                         \
     --upload "$datadir"/launch-virt-p2v:/usr/bin/               \
     --chmod 0755:/usr/bin/launch-virt-p2v                       \
