Use udev if available (Guido Gunter).
Added support for Fedora's udev (Richard Jones).

diff --git a/appliance/init b/appliance/init
--- a/appliance/init
+++ b/appliance/init
@@ -4,29 +4,38 @@ echo Starting /init script ...
 
 PATH=/sbin:/usr/sbin:$PATH
 
-mount -t tmpfs none /dev
-mkdir /dev/pts /dev/shm /dev/mapper
-# Must do each MAKEDEV individually, because if one device fails,
-# MAKEDEV will quit without creating the rest (RHBZ#507374).
-for dev in mem null port zero core full ram tty console fd \
-  hda hdb hdc hdd sda sdb sdc sdd loop sd; do
-  MAKEDEV $dev ||:
-done
-mknod /dev/ptmx c 5 2;    chmod 0666 /dev/ptmx
-mknod /dev/random c 1 8;  chmod 0666 /dev/random
-mknod /dev/urandom c 1 9; chmod 0444 /dev/urandom
-
 mount -t proc /proc /proc
 mount -t sysfs /sys /sys
-mount -t devpts -o gid=5,mode=620 /dev/pts /dev/pts
 
-ln -sf /proc/self/fd/0 /dev/stdin
-ln -sf /proc/self/fd/1 /dev/stdout
-ln -sf /proc/self/fd/2 /dev/stderr
+if [ -x /etc/init.d/udev ]; then
+  /etc/init.d/udev start
+elif [ -x /sbin/start_udev ]; then
+  /sbin/start_udev
+else
+  echo No udev, creating /dev manually
+  mount -t tmpfs none /dev
+  mkdir /dev/pts /dev/shm /dev/mapper
+  mount -t devpts -o gid=5,mode=620 /dev/pts /dev/pts
+  # Must do each MAKEDEV individually, because if one device fails,
+  # MAKEDEV will quit without creating the rest (RHBZ#507374).
+  for dev in mem null port zero core full ram tty console fd \
+    hda hdb hdc hdd sda sdb sdc sdd loop sd; do
+    MAKEDEV $dev ||:
+  done
+  mknod /dev/ptmx c 5 2;    chmod 0666 /dev/ptmx
+  mknod /dev/random c 1 8;  chmod 0666 /dev/random
+  mknod /dev/urandom c 1 9; chmod 0444 /dev/urandom
+  ln -sf /proc/self/fd/0 /dev/stdin
+  ln -sf /proc/self/fd/1 /dev/stdout
+  ln -sf /proc/self/fd/2 /dev/stderr
 
-modprobe virtio_pci
-modprobe virtio_net
-modprobe dm_mod ||:
+  modprobe virtio_pci
+  modprobe virtio_net
+  modprobe dm_mod ||:
+fi
+
+mount
+ls -l /dev
 
 /sbin/ifconfig lo 127.0.0.1
 /sbin/ifconfig eth0 10.0.2.10
