Fix --enable-valgrind-daemon option.
Don't add the "valgrind channel" to the appliance.

Just dump out the valgrind.log to stderr while the daemon is running.

Ensure that if valgrind tests fail in the appliance, that we don't
exit with success in the library by checking for a canary message in
the verbose daemon logs.

This allows the option to be used routinely by developers.

diff --git a/appliance/init b/appliance/init
--- a/appliance/init
+++ b/appliance/init
@@ -135,21 +135,17 @@ fi
 
 if ! grep -sq guestfs_rescue=1 /proc/cmdline; then
   # Run the daemon under valgrind if ./configure --enable-valgrind-daemon
-  vg_channel=/dev/virtio-ports/org.libguestfs.valgrind
-  if [ -w $vg_channel ]; then
+  if grep -sq guestfs_valgrind_daemon=1 /proc/cmdline; then
     if [ -r /etc/guestfsd.suppressions ]; then
       suppressions="--suppressions=/etc/guestfsd.suppressions"
     fi
-    exec 3>$vg_channel
-    vg="valgrind --leak-check=full --log-fd=3 --error-exitcode=119 --max-stackframe=8388608 --child-silent-after-fork=yes $suppressions"
+    vg="valgrind --leak-check=full --error-exitcode=119 --max-stackframe=8388608 --child-silent-after-fork=yes $suppressions"
     echo "enabling valgrind: $vg"
   fi
 
-  # The host will kill qemu abruptly if guestfsd shuts down normally
+  # Run guestfsd, under valgrind if asked.
   $vg guestfsd
-
-  # Otherwise we try to clean up gracefully. For example, this ensures that a
-  # core dump generated by the guest daemon will be written to disk.
+  if [ $? -eq 119 ]; then echo "DAEMON VALGRIND FAILED"; fi
 else
   # Use appliance in rescue mode, also used by the virt-rescue command.
   eval $(grep -Eo 'TERM=[^[:space:]]+' /proc/cmdline)
